<?php
/**
  * @file
  * Module that will import classes from KualiCo Student API
  */

/**
  * Implements hook_student_menu()
  *
  */
function kualico_student_menu() {
  $items = array();

  $items['admin/config/content/kualico_student'] = array(
    'title' => t('KualiCo Student'),
    'description' => t('Configuration of the KualiCo Student Module'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kualico_student_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM
  );
}

function kualico_student_config_form($form, &$form_state) {
  $form['kualico_student_api_url'] = array(
    '#type' => 'textfield',
    '#title' => t('API Url'),
    '#default_value' => variable_get(
    'kualico_student_api_url',
    'example: http://monsters.kuali.co/api/cm'
    ),
    '#size' => 64,
    '#description' => t('Enter your API URL'),
    '#required' => TRUE
  );

  $form['kualico_student_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('API Key'),
    '#default_value' => t('Manage your API-keys in your KualiCo Auth Profile'),
    '#size' => 250,
    '#maxlength' => 200,
    '#description' => t('Enter your API key'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
  * Hit api based on provided config values
  *
  * @param url
  * Route to hit. A list of available routes can be found in the API docs at
  * {yourdomain}.kuali.co/cm/doc/index.html
  * @param method
  * HTTP method. Defaults to 'GET'
  * @param body
  * Payload to send with request. Default to none
  */
function kualico_student_ajax($url, $method = 'GET', $body = null) {
  $context = array(
    'http' => array(
      'method' => $method,
      'header' => 'Authorization: Bearer' . variable_get('kualico_student_api_key'),
      'body' => $body
    )
  );
  $context = stream_context_create($context);
  $response = json_decode(
    file_get_contents(
      variable_get('kualico_student_api_url') . $url,
      false,
      $context
    ),
    TRUE
  );

  return $response;
}

/**
  * Send a 'GET' request
  *
  * @param url
  * Url to hit.
  */
function kualico_student_get($url) {
  return kualico_student_ajax($url, 'GET');
}

/**
  * Send a 'GET' request
  *
  * @param url
  * Url to hit.
  */
function kualico_student_post($url, $body) {
  return kualico_student_ajax($url, 'POST', $body);
}

/**
  * Send a 'GET' request
  *
  * @param url
  * Url to hit.
  */
function kualico_student_put($url, $body) {
  return kualico_student_ajax($url, 'PUT', $body);
}

/**
  * Send a 'GET' request
  *
  * @param url
  * Url to hit.
  */
function kualico_student_delete($url, $body) {
  return kualico_student_ajax($url, 'DELETE', $body);
}

/**
  * Implements form_validate()
  * Displays hepl and module information
  *
  * @param form
  * Which form is being validated
  * @param form_state
  * State of the form to be validated.
  */
function kualico_student_config_form_validate($form, &$form_state) {
  $api_key = $form_state['values']['kualico_student_api_key'];
  $api_url = $form_state['values']['kualico_student_api_url'];
  if($api_key === t('Manage your API-keys in your KualiCo Auth Profile')) {
    form_set_value($form['kualico_student_api_key'], variable_get('kualico_student_api_key', '####NOT A REAL KEY####'), $form_state);
  } else if (!_kualico_student_validate_api_key($form_state)){
    form_set_error(
    'kualico_student_api_key',
    t('API Key must follow the format: [random characters].[random characters].[random characters]'));
  }
  if (substr($api_url, -1) !== '/') {
    $api_url .= '/';
    form_set_value($form['kualico_student_api_url'], $api_url, $form_state);
  }
}

function _kualico_student_validate_api_key(&$form_state) {
  $regex = '/^\S+[.]\S+[.]\S+$/';
  return preg_match($regex, $form_state['values']['kualico_student_api_key']);
}

/**
  * Implements hook_help()
  * Displays hepl and module information
  *
  * @param path
  * Which path of the site we're using to display this help
  * @param arg
  * Array that holds the current path as returned from arg() function
  */
function kualico_student_permission() {
  return array(
    'acces kualico_student content' => array(
      'title' => t('Access content for the Kualico Student module'),
    )
  );
}
